### ISSUE TITLE
Is there going to be a 1.18.2 update?

### ISSUE THREAD

**Issue by EGOIST1372** [MrNerdy42/keywizard-fabric#2]
thanks in advance <3

**Comment by MrNerdy42** [comment]
You're welcome! I'm glad you like what I do :) 

I just want to let you know that questions like this should be posted over on CurseForge, as they aren't really actionable issues. 

However, since you're already here, I'll quick answer your question: I have plans to update to 1.18.2 after I'm finished re-adding core functionality and re-familiarizing myself with the Minecraft modding scene. Keep an eye on the CurseForge and on this repo for my progress.

**Comment by EGOIST1372** [comment]
keep up the good work
thanks
